name: Code Review
on: pull_request

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: "Install python requirements"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: "Check style"
        run: |
          black --check --verbose .
      - name: "Test code"
        run: |
          python -m unittest discover -s tests/unit
