name: Code Review
on: pull_request

jobs:
  black:
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install black
      - run: |
          black --check --verbose .