# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Test plugp100 library

on:
  push:
    branches:
      - "main"

jobs:
  dependecies_job:
    runs-on: ubuntu-latest
    name: Build on

    steps:
      - run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - uses: docker://multiarch/ubuntu-core:arm64-bionic
        with:
          args: 'uname -a'

      - uses: actions/checkout@v2.1.0